#!/usr/bin/env python3
"""Keep the native proof program identical to the root Cairo channel rules."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for name, expected in [("rules", 2), ("channel_protocol", 1)]:
    source = (ROOT / f"src/{name}.cairo").read_text()
    assert source.count("Introspect, DojoStore") == expected
    content = "// Generated by offchain/prepare.py; edit the root source.\n" + source.replace("Introspect, DojoStore, ", "")
    destination = ROOT / f"offchain/cairo/src/{name}.cairo"
    if "--check" in sys.argv:
        assert destination.read_text() == content, f"Stale generated source: {destination}"
    else:
        destination.write_text(content)
print("Channel rules and protocol sources match")
