// Writes ratings/src/tests/audit_vectors.cairo: random extreme cases and a long
// one-player sequence from the SDK's integer update, so test_audit.cairo checks
// the Cairo math bit for bit beyond the hand-picked vectors.
//
//   node offchain/ratings/audit/audit-vectors.mjs && (cd ratings && scarb test -f audit)
import { writeFile } from 'node:fs/promises';
import * as r from '../../sdk/src/rating.mjs';

const { ONE, MU_MIN, MU_MAX, MIN_PHI, PHI0, MU_T } = r;
const U64 = (1n << 64n) - 1n;
let seed = 0xa0d17n;
const rnd = () => { seed ^= seed << 13n; seed &= U64; seed ^= seed >> 7n; seed ^= seed << 17n; seed &= U64; return seed; };
const uni = () => Number(rnd() >> 11n) / 2 ** 53;
const pick = xs => xs[Number(rnd() % BigInt(xs.length))];
const range = (lo, hi) => lo + rnd() % (hi - lo + 1n);
const T0 = 1_700_000_000n;

const mu = () => { const k = uni(); return k < 0.2 ? MU_MIN : k < 0.4 ? MU_MAX : k < 0.5 ? pick(MU_T.slice(0, 39)) : range(MU_MIN, MU_MAX); };
const phi = () => { const k = uni(); return k < 0.15 ? 0n : k < 0.35 ? MIN_PHI : k < 0.5 ? PHI0 : k < 0.55 ? ONE : range(MIN_PHI, PHI0); };
const state = last => { const p = phi(); return p === 0n ? r.start(Number(range(1n, 4n))) : { mu: mu(), phi: p, last }; };
const cases = [];
// Hand-picked corners first.
for (const [bl, wl, t] of [[0n, 0n, 0n], [U64, U64, U64], [U64, 0n, 0n], [0n, 0n, U64], [T0, T0, T0 + (1n << 30n)],
  [T0, T0, T0 + (1n << 30n) + 1n], [T0, T0 - 1n, T0 - 1n], [T0 + 100n, T0 + 50n, T0]])
  for (const [bm, wm] of [[MU_MIN, MU_MAX], [MU_MAX, MU_MIN], [MU_MIN, MU_MIN], [MU_MAX, MU_MAX]])
    for (const [bp, wp] of [[MIN_PHI, MIN_PHI], [PHI0, MIN_PHI], [MIN_PHI, PHI0], [PHI0, PHI0]])
      for (const result of [0, 2])
        cases.push([{ mu: bm, phi: bp, last: bl }, { mu: wm, phi: wp, last: wl }, result, t]);
while (cases.length < 900) {
  const last = pick([0n, T0, U64, range(0n, U64), range(T0 - 400n * 86400n, T0)]);
  const t = pick([last, last + 1n, last + 86400n, last + range(0n, 1n << 31n), last - range(0n, 1000n), 0n, U64]);
  const tt = t < 0n ? 0n : t > U64 ? U64 : t;
  cases.push([state(last), state(pick([last, range(0n, tt)])), Number(rnd() % 3n), tt]);
}
// One player's 400 games: a strong player pinned at 9d who keeps winning, then
// losing streaks, then same-second games, then decades of idle.
let hero = { mu: MU_MAX - 1000n, phi: ONE / 3n, last: T0 };
const seq = [];
let t = T0;
for (let i = 0; i < 400; i++) {
  t += i < 100 ? 3600n : i < 200 ? 0n : i < 300 ? range(0n, 20n * 86400n) : range(0n, 3n * 365n * 86400n);
  const opp = { mu: i % 7 === 0 ? MU_MIN : range(MU_MIN, MU_MAX), phi: range(MIN_PHI, PHI0), last: t - range(0n, 86400n) };
  const result = i < 100 ? 2 : i < 150 ? 0 : Number(rnd() % 3n);
  const out = r.update(hero, opp, result, t);
  seq.push({ opp, result, t, out: out.black });
  hero = out.black;
}

const R = x => `Rating { mu: ${x.mu}, phi: ${x.phi}, last: ${x.last} }`;
const lines = [
  '// Generated by offchain/ratings/audit/audit-vectors.mjs from offchain/sdk/src/rating.mjs.',
  'use crate::math::Rating;',
  '',
  '/// (black, white, result, t, black_out, white_out, p)',
  'pub fn cases() -> Array<(Rating, Rating, u8, u64, Rating, Rating, i128)> {',
  '    array![',
  ...cases.map(([b, w, res, tt]) => {
    const u = r.update(b, w, res, tt);
    return `        (${R(b)}, ${R(w)}, ${res}, ${tt}, ${R(u.black)}, ${R(u.white)}, ${u.p}),`;
  }),
  '    ]',
  '}',
  '',
  `pub fn hero_start() -> Rating { ${R({ mu: MU_MAX - 1000n, phi: ONE / 3n, last: T0 })} }`,
  '',
  '/// (opponent, hero\'s result, t, hero after)',
  'pub fn hero() -> Array<(Rating, u8, u64, Rating)> {',
  '    array![',
  ...seq.map(g => `        (${R(g.opp)}, ${g.result}, ${g.t}, ${R(g.out)}),`),
  '    ]',
  '}',
  '',
];
await writeFile(new URL('../../../ratings/src/tests/audit_vectors.cairo', import.meta.url), lines.join('\n'));
console.log(`wrote ${cases.length} cases and a ${seq.length}-game sequence`);
