[package]
name = "surround_offchain"
version = "0.1.0"
edition = "2024_07"
cairo-version = "=2.18.0"

[dependencies]
starknet = "=2.18.0"
referee = { path = "../../../referee/core" }
referee_adapter = { path = "../../../referee/adapter/referee_adapter" }
surround_rules = { path = "../../rules" }

[dev-dependencies]
snforge_std = "=0.63.0"
referee_testing = { path = "../../../referee/testing" }

[lib]

[[target.starknet-contract]]
casm = true

[scripts]
test = "snforge test"
