[package]
name = "surround_offchain"
version = "0.1.0"
edition = "2024_07"
cairo-version = "=2.18.0"

[dependencies]
starknet = "=2.18.0"
referee = { git = "https://github.com/broody/referee.git", rev = "282d087" }
referee_adapter = { git = "https://github.com/broody/referee.git", rev = "282d087" }
surround_rules = { path = "../../rules" }

[dev-dependencies]
snforge_std = "=0.63.0"
referee_testing = { git = "https://github.com/broody/referee.git", rev = "282d087" }

[lib]

[[target.starknet-contract]]
casm = true

[scripts]
test = "snforge test"
